### ISSUE TITLE
where is the Path/To/Dataset_Home_Directory/Food101/texts_txt/filet_mignon/filet_mignon_226.txt?  you don't give it

### ISSUE THREAD

**Issue by Seaz9** [Vincent-ZHQ/UniS-MMC#1]

**Comment by Vincent-ZHQ** [comment]
'Path/To/Dataset_Home_Directory/' is a path to the home directory of your dataset. You have to change it to your own directory. 'texts_txt/filet_mignon/filet_mignon_226.txt' is a text file from the Food101 dataset. This dataset should be downloaded and prepared by yourself.

In short. you download the Food101 dataset and change the directory name to yours.

**Comment by Seaz9** [comment]
Hello, author. I spent the whole day yesterday searching for the download link of the UPMC-Food-101 txt files. Unfortunately, I couldn't find it. I only downloaded the UPMC-Food-101 images and the txt file containing titles from Kaggle. I couldn't locate the individual .txt download links for each image. Could you please share a Google Drive link or your download link with me? Thank you very much.

**Comment by Vincent-ZHQ** [comment]
I downloaded it from the official website that I provided on the home page. But I tried, and it does not work now. Maybe the website has been closed. I think you can ask for help from the dataset author first for help. (The link is http://visiir.lip6.fr/data/public/UPMC_Food101.tar.gz)

**Comment by Seaz9** [comment]
Dear author,

Hello. Yes, I am unable to access the link to the dataset's official website either. I have also posed this question to the dataset's author, but they have not responded to me. Could you please provide me with the non-image text files of the UPMC_Food101 dataset? You can share them with me through a Google Drive or Baidu Cloud link. I am a student and currently in urgent need of getting this code to work. Thank you very much.

Best regards

**Comment by Seaz9** [comment]
Dear author,

I reached out to the original creators of the UPMC_Food101 dataset regarding the download link for the txt files. Unfortunately, I have not received a response from them yet. If possible, could you please share the txt files from your local copy of the Food101 dataset with me? You can use Google Drive or Baidu Drive to provide the link. Here's my Google email:mufeng696@gmail.com. I understand this might be an inconvenience, but I'm hoping for your assistance. I'm interested in using my own dataset with your model for research purposes and to explore opportunities for improvements and innovations. Thank you very much.

Best regards
