### ISSUE TITLE
pretained问题

### ISSUE THREAD

**Issue by 1137292294** [Vincent-ZHQ/UniS-MMC#2]
麻烦想问下这个文件夹里的预训练模型是要自己下载嘛，代码里没有直接调用？复现的时候报错Can't load tokenizer for 'Path/To/Pretrained/bert_base_uncased/'

**Comment by Vincent-ZHQ** [comment]
你可以改成自动缓存的，我这里设成本地路径了，需要自己下载，我的huggingface上的
https://huggingface.co/bert-base-uncased
